name: Update F1 Database

on:
  schedule:
    # Ejecutar todos los viernes, sábados, domingos y lunes a las 00:00 UTC
    - cron: '0 0 * * 5'  # Viernes
    - cron: '0 0 * * 6'  # Sábado
    - cron: '0 0 * * 0'  # Domingo
    - cron: '0 0 * * 1'  # Lunes
  workflow_dispatch:  # Permitir ejecución manual desde la interfaz de GitHub

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      # Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Ajusta según la versión que uses

      # Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests supabase python-dotenv

      # Crear archivo .env con secretos de GitHub
      - name: Create .env file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env
          echo "SUPABASE_SERVICE_KEY=${{ secrets.SUPABASE_SERVICE_KEY }}" >> .env

      # Ejecutar el script con reintentos para manejar el error 429
      - name: Run script with retries
        run: |
          for attempt in {1..5}; do
            echo "Intento $attempt de 5"
            python main.py && break  # Si tiene éxito, salir del bucle
            if [ $? -eq 429 ]; then
              echo "Error 429 detectado. Esperando antes de reintentar..."
              sleep $((attempt * 60))  # Espera incremental: 60s, 120s, 180s, 240s, 300s
            else
              echo "Error diferente al 429. Terminando."
              exit 1
            fi
            if [ $attempt -eq 5 ]; then
              echo "Fallo tras 5 intentos. Terminando."
              exit 1
            fi
          done
